name: DQO-MAP
channels:
  - pytorch3d
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.7.1
  - ffmpeg
  - pillow=9.4.0
  - pip
  - plyfile
  - python=3.9.21
  - pytorch=1.13.1
  - pytorch3d
  - tensorboard
  - torchaudio=0.13.1
  - torchvision=0.14.1
  - tqdm
  - pip:
      - glfw
      - glm
      - gputil
      - matplotlib
      - numpy
      - open3d
      - opencv-python
      - pandas
      - pytz
      - scipy
      - pyyaml
      - submodules/cuda_utils
      - submodules/diff-gaussian-rasterizer-depth
      - submodules/simple-knn
