parent: "configs/base.yaml"
device_list: [1]
save_path: "output/RO-MAP/debug"

type: "RO-MAP"
source_path: "data/RO-MAP_data/room"

uniform_sample_num: 100000   # 增加点云密度
pcd_densify: True

# state manage
stable_confidence_thres: 100
unstable_time_window: 120
memory_length: 5

# optimize params:
gaussian_update_iter: 100     # 增加迭代次数
gaussian_update_frame: 6
position_lr : 0.001
feature_lr : 0.0005
opacity_lr : 0.000
scaling_lr : 0.004
rotation_lr : 0.001
final_global_iter: 40        # 增加全局优化迭代

# track params
icp_use_model_depth: True
icp_normal_threshold: 20
icp_sample_distance_threshold: 0.01
icp_sample_normal_threshold: 0.01

feature_lr_coef: 4.0
scaling_lr_coef: 4.0
rotation_lr_coef: 4.0
semantic_lr_coef: 4.0

# 渲染优化参数
renderer_opaque_threshold_eval: 0.05
resolution_scales: [1.0]

# Poisson 重建参数
poisson_depth: 10
simplify_triangles: 200000
density_quantile: 0.01
mesh_smooth_iter: 10
mesh_smooth_lambda: 0.5